
ingredient_list = ['[jar, Alfredo, sauce],
[black, pepper],
[Cheddar, cheese],
[container, ricotta, cheese],
[Parmesan, cheese],
[egg, lightly],
[no, boil, lasagna, noodles],
[mozzarella, cheese]],
[[jumbo, pasta, shells],
[eggs],
[container, ricotta, cheese],
[shredded, mozzarella, cheese],
[Parmesan, cheese],
[parsley],
[],
[black, pepper],
[jar, pasta, sauce],
[mushrooms]],
[[lasagna, noodles],
[mushrooms],
[green, bell, pepper],
[onion],
[cloves, garlic],
[vegetable, oil],
[pasta, sauce],
[basil],
[container, part, skim, ricotta, cheese],
[mozzarella, cheese],
[eggs],
[Parmesan, cheese]],
[[linguine, pasta],
[butter],
[heavy, cream],
[black, pepper],
[Parmesan, cheese],
[pesto],
[shrimp]],
[[garlic, scapes],
[freshly, Romano, cheese],
[parsley],
[walnuts],
[olive, oil],
[lemon, juice],
[box, fettuccine, pasta],
[shrimp],
[salt, black, pepper],
[lemon, wedges]],
[[gnocchi],
[olive, oil],
[radicchio],
[heavy, whipping, cream],
[Gorgonzola, cheese],
[nutmeg],
[salt, black, pepper]],
[[penne, fusilli, pasta],
[cloves, garlic],
[extra, virgin, olive, oil],
[broccoli],
[cauliflower],
[salt],
[low, sodium, vegetable, chicken, broth],
[butter],
[no, salt, cannellini, beans],
[black, pepper],
[Parmigiano, Reggiano, cheese]],
[[bucatini, pasta],
[extra, virgin, olive, oil],
[garlic, cloves],
[guanciale, pork, cheek],
[red, onion],
[red, pepper, flakes],
[San, Marzano, tomatoes],
[salt, black, pepper],
[freshly, Pecorino, Romano, cheese]],
[[butter],
[onion],
[basil],
[red, pepper, flakes],
[salt],
[black, pepper],
[chicken, thighs],
[linguine, pasta],
[spinach, dry],
[Parmesan, cheese]],
[[bow, tie, pasta],
[olive, oil],
[sweet, Italian, sausage],
[red, pepper, flakes],
[onion],
[cloves, garlic],
[Italian, plum, tomatoes, coarsely],
[heavy, cream],
[salt],
[parsley]],
[[penne, pasta],
[butter],
[extra, virgin, olive, oil],
[onion],
[cloves, garlic],
[red, bell, pepper],
[portobello, mushrooms],
[medium, shrimp],
[jar, Alfredo, sauce],
[Romano, cheese],
[cream],
[cayenne, pepper, more],
[Salt, pepper],
[parsley]],
[[cheese, tortellini],
[tomatoes, garlic, onion],
[spinach],
[salt],
[pepper],
[basil],
[garlic],
[flour],
[milk],
[heavy, cream],
[Parmesan, cheese]],
[[],
[uncooked, lasagna, noodles],
[onion],
[cloves, garlic],
[broth],
[rosemary],
[artichoke, hearts],
[spinach, dry],
[jar, tomato, pasta, sauce],
[mozzarella, cheese],
[herb, garlic, feta]],
[[uncooked, penne, pasta],
[extra, virgin, olive, oil],
[cloves, garlic],
[red, pepper, flakes],
[tomatoes],
[salt],
[vodka],
[heavy, whipping, cream],
[parsley],
[sweet, Italian, sausage]],
[[rice, noodles],
[sugar],
[vinegar],
[fish, sauce],
[tamarind, paste],
[vegetable, oil],
[chicken, breast, strips],
[vegetable, oil],
[garlic],
[eggs],
[sugar],
[salt],
[coarsely, peanuts],
[bean, sprouts],
[chives],
[paprika],
[lime, wedges]],
[[beef], [Oriental, ramen, noodles], [tomatoes], [whole, corn]],
[[canola, oil],
[oil],
[chicken, breast, bite, size],
[cloves, garlic],
[Asian, chile, paste],
[soy, sauce],
[canola, oil],
[medium, cabbage, thinly],
[onion],
[carrots, matchsticks],
[salt],
[yakisoba, noodles],
[ginger]],
[[egg, noodles],
[turkey],
[onion],
[sauce],
[Italian, seasoning],
[milk],
[cream, cheese],
[parsley],
[clove, garlic],
[part, skim, mozzarella, cheese]],
[[chicken, broth, vegetable, broth],
[medium, onion],
[carrots],
[water],
[soy, sauce],
[serrano, chile, pepper, finely],
[cloves, garlic],
[ginger, root],
[rice, noodles],
[cabbage],
[shiitake, mushrooms],
[zucchini],
[sugar, pea, pods, diagonally],
[carrots],
[cornstarch],
[cold, water],
[Sliced, green, onions]],
[[egg, noodles],
[tuna],
[celery],
[green, onions],
[sour, cream],
[mustard],
[mayonnaise],
[thyme],
[salt],
[zucchini],
[Monterey, Jack, cheese],
[tomato]],
[[uncooked, spaghetti],
[cornstarch],
[vegetable, broth],
[creamy, peanut, butter],
[soy, sauce],
[honey],
[brown, sugar],
[sesame, oil],
[ginger],
[red, pepper],
[sake],
[vegetable, oil],
[cloves, garlic],
[onion],
[broccoli],
[carrots],
[red, bell, pepper],
[sugar, peas]],
[[pkg, size, sweet, potato, vermicelli],
[sodium, soy, sauce],
[brown, sugar],
[boiling, water],
[vegetable, oil],
[sesame, seeds]],
[[sugar],
[vinegar],
[soy, sauce],
[tamarind, pulp],
[rice, noodles],
[vegetable, oil],
[garlic],
[eggs],
[firm, tofu, strips],
[sugar],
[salt],
[peanuts],
[oriental, radish],
[chives],
[paprika],
[bean, sprouts],
[lime, wedges]],
[[cloves, garlic],
[loosely, cilantro],
[jalapeno, pepper],
[sugar],
[lime, juice],
[vegetarian, fish, sauce],
[rice, noodles],
[carrots],
[cucumber, lengthwise],
[mint],
[leaves, cabbage],
[unsalted, peanuts],
[mint]],
[[udon, noodles],
[chicken, broth],
[ginger, root],
[soy, sauce],
[peanut, butter],
[honey],
[oil],
[cloves, garlic],
[whole, rotisserie, chicken, skinned, meat],
[red, bell, pepper, thinly],
[green, onions],
[peanuts],
[cilantro]],
[[rice, noodles],
[vegetable, oil],
[onion, finely],
[cloves, garlic],
[cooked, chicken, breast, meat],
[cabbage, thinly],
[carrot, thinly],
[soy, sauce],
[lemons, wedges]],
[[plain, yogurt],
[mint, leaves],
[cloves, garlic],
[beef],
[onion],
[water],
[carrot],
[salt],
[black, pepper],
[coriander],
[cumin],
[wrappers],
[tomato, paste],
[red, pepper, flakes],
[water],
[yellow, split, peas],
[red, pepper, flakes],
[coriander],
[cumin],
[chicken, bouillon],
[water]],
[[Chinese, wheat, noodles],
[asparagus],
[canola, oil],
[cloves, garlic],
[ginger, root],
[water],
[cornstarch],
[Chinese, rice, wine],
[soy, sauce],
[fermented, black, beans],
[stems],
[dark, sesame, oil],
[salt, pepper]],
[[flour], [salt], [eggs], [milk], [butter]],
[[vegetable, oil],
[wine, vinegar],
[sugar],
[chicken, ramen, noodles, packet],
[salt],
[black, pepper],
[sesame, seeds],
[],
[medium, cabbage],
[green, onions]],
[[butter],
[onion],
[portobello, mushrooms],
[vegetable, broth],
[sour, cream],
[flour],
[parsley],
[egg, noodles]],
[[rice, vermicelli],
[rice, wrappers, diameter],
[cooked, shrimp],
[Thai, basil],
[mint, leaves],
[cilantro],
[leaves, lettuce],
[fish, sauce],
[water],
[lime, juice],
[clove, garlic],
[sugar],
[garlic, chili, sauce],
[hoisin, sauce],
[finely, peanuts]],
[[asparagus],
[egg, noodles],
[cloves, garlic],
[extra, virgin, olive, oil],
[butter],
[lemon, juice],
[medium, shrimp],
[mushrooms, thinly],
[Parmesan, cheese],
[salt, pepper]],
[[frozen, brown, potatoes],
[pork, sausage],
[onion],
[eggs],
[milk],
[onion],
[garlic],
[salt, black, pepper],
[Cheddar, cheese]],
[[plain, bread, crumbs],
[milk],
[olive, oil],
[onion],
[beef],
[pork],
[eggs],
[bunch, parsley],
[cloves, garlic],
[],
[black, pepper],
[red, pepper, flakes],
[Italian, herb, seasoning],
[Parmesan, cheese]],
[[Italian, sausage],
[onion],
[garlic],
[Italian, seasoning],
[fluid, broth],
[carrot],
[spinach],
[uncooked, pearl, barley]],
[[jumbo, buttermilk, biscuits],
[Jimmy, Dean, Original, Hearty, Pork, Sausage, Crumbles],
[flour],
[milk],
[Salt, black, pepper]],
[[chicken, breast],
[salt],
[lemon, pepper, seasoning],
[vegetable, oil],
[strips, bacon],
[onion],
[brown, sugar],
[Colby, Monterey, Jack, cheese]],
[[baking, potatoes],
[lean, bacon],
[mild, Cheddar, cheese],
[sour, cream],
[milk],
[unsalted, butter],
[chives],
[salt],
[black, pepper],
[garlic],
[mild, Cheddar, cheese]],
[[baby, back, ribs],
[salt, black, pepper],
[water],
[onion],
[clove, garlic],
[bottle, barbeque, sauce]],
[[steak, rub], [balsamic, vinegar], [olive, oil], [pork, loin, roast]],
[[butter],
[andouille, sausage],
[paprika],
[cumin],
[cayenne, pepper],
[tomatoes],
[green, bell, pepper],
[stalks, celery],
[green, onions, thinly],
[salt],
[bay],
[uncooked, brown, rice],
[chicken, stock],
[shrimp],
[salt, black, pepper]],
[[ham],
[bourbon, whiskey],
[brown, sugar],
[pineapple, juice],
[honey],
[cloves, garlic],
[water],
[rings]],
[[vegetable, oil],
[pork, shoulder, several],
[kosher, salt],
[onion],
[clove, garlic],
[lime, juice],
[chili],
[oregano],
[cumin],
[chicken, broth]],
[[Spice, Rub],
[whole, fennel, seeds],
[cloves, garlic],
[finely, sage, leaves],
[freshly, black, pepper],
[rosemary],
[kosher, salt, more],
[red, pepper, flakes],
[lemon],
[olive, oil],
[pork, tenderloin],
[strips, bacon]],
[[olive, oil],
[mushrooms],
[olive, oil],
[pork, loin, chops],
[cloves, garlic],
[onion],
[Italian, tomatoes, undrained],
[basil],
[oregano],
[salt],
[black, pepper],
[water, necessary],
[green, bell, pepper]],
[[olive, oil],
[bacon],
[onion],
[clove, garlic],
[lean, beef],
[pork],
[mushrooms],
[carrots],
[stalk, celery],
[Italian, plum, tomatoes],
[tomato, sauce],
[dry, wine],
[chicken, stock],
[basil],
[oregano],
[salt, pepper],
[pasta]],
[[frozen, bread, dough],
[Parmesan, cheese],
[vegetable, oil],
[egg, yolks],
[parsley],
[oregano],
[garlic],
[black, pepper],
[pepperoni],
[Virginia, ham],
[provolone, cheese],
[vegetable, oil],
[green, bell, pepper],
[onion],
[mushrooms],
[egg],
[grated, Parmesan, cheese],
[Italian, seasoning]],
[[jumbo, buttermilk, biscuits],
[Jimmy, Dean, Original, Hearty, Pork, Sausage, Crumbles],
[flour],
[milk],
[Salt, black, pepper]],
[[baby, back, ribs],
[salt, black, pepper],
[water],
[onion],
[clove, garlic],
[bottle, barbeque, sauce]],
[[butter],
[onion],
[ribs, celery],
[cloves, garlic],
[ham],
[bay],
[split, peas],
[chicken, stock],
[water],
[salt, black, pepper]],
[[brown, sugar],
[fajita, seasoning, Fiesta],
[Hungarian, sweet, paprika],
[racks, pork, spareribs, fat],
[beer],
[cloves, garlic],
[honey],
[Worcestershire, sauce],
[prepared, brown, mustard]],
[[Brussels, sprouts],
[extra, virgin, olive, oil],
[pure, maple, syrup],
[bacon],
[salt],
[freshly, black, pepper]],
[[bacon],
[sweet, onion],
[shredded, brown, potatoes],
[eggs, lightly],
[Cheddar, cheese],
[curd, cottage, cheese],
[Swiss, cheese]],
[[cut, bacon],
[yellow, onion],
[beef],
[cloves, garlic],
[cumin],
[kidney, beans],
[fire, tomatoes],
[water],
[chili],
[liquid, smoke, flavoring],
[salt, black, pepper],
[hot, pepper, sauce, Tabasco]],
[[barbeque, rub, more],
[bone, pork, shoulder, blade, roast],
[liquid, smoke, flavoring],
[water],
[barbeque, sauce],
[salt, freshly, black, pepper],
[soft, hamburger, buns],
[barbeque, sauce]],
[[vegetable, oil],
[pork, shoulder, several],
[kosher, salt],
[onion],
[clove, garlic],
[lime, juice],
[chili],
[oregano],
[cumin],
[chicken, broth]],
[[hickory, bacon, crosswise],
[jalapeno, peppers, lengthwise],
[tub, cream, cheese, room, temperature],
[Cheddar, cheese],
[Worcestershire, sauce]],
[[brown, sugar],
[rice, vinegar],
[maple, syrup],
[black, pepper],
[cut, bacon]],
[[eggs],
[vegetable, oil],
[onion],
[sour, cream],
[mayonnaise],
[ranch],
[mustard],
[garlic],
[onion],
[lemon, pepper, seasoning],
[bacon, bits],
[finely, Cheddar, cheese],
[paprika]],
[[Brussels, sprouts],
[bacon],
[butter],
[olive, oil],
[cloves, garlic],
[sodium, chicken, broth],
[salt],
[black, pepper],
[butter]],
[[bacon],
[broccoli],
[Cheddar, cheese],
[red, onion],
[red, wine, vinegar],
[sugar],
[black, pepper],
[salt],
[mayonnaise],
[lemon, juice]],
[[cumin],
[chili],
[paprika],
[salt, pepper],
[baby, back, pork, ribs],
[barbeque, sauce]],
[[pork, tenderloins], [garlic], [salt], [black, pepper], [barbeque, sauce]],
[[ready, ham], [whole, cloves], [dark, corn, syrup], [honey], [butter]],
[[cloves, garlic],
[coarse, salt],
[olive, oil],
[whole, black, peppercorns],
[pork, tenderloin, medallions],
[red, bell, peppers],
[wine],
[lemons]],
[[pork, butt],
[salt],
[sugar],
[soy, sauce],
[egg],
[green, onions],
[vegetable, oil],
[cornstarch],
[vegetable, oil],
[stalks, celery],
[medium, green, bell, pepper],
[medium, onion, wedges],
[sugar],
[salt],
[water],
[salt],
[sugar],
[apple, cider, vinegar],
[ketchup],
[soy, sauce],
[pineapple, undrained],
[cornstarch],
[water]],
[[pork, baby, back, ribs],
[black, pepper],
[salt],
[red, pepper],
[barbecue, sauce],
[bottles, porter, beer, room, temperature]],
[[olive, oil],
[pork, tenderloins],
[Roma, plum, tomatoes],
[green, olives],
[dry, wine],
[rosemary],
[cloves, garlic],
[salt],
[pepper],
[heavy, cream]],
[[potatoes],
[celery],
[finely, onion],
[cooked, ham],
[water],
[chicken, bouillon],
[salt],
[black, pepper],
[butter],
[flour],
[milk]],
[[pork, chops],
[garlic],
[salt],
[egg],
[flour],
[Italian, bread, crumbs],
[olive, oil],
[cream, mushroom, soup],
[milk],
[wine]],
[[pork, tenderloin],
[fluid, root, beer],
[your, favorite, barbecue, sauce],
[hamburger, buns, lightly]],
[[broth], [pork, ribs], [bottle, barbeque, sauce]],
[[bow, tie, pasta],
[olive, oil],
[sweet, Italian, sausage],
[red, pepper, flakes],
[onion],
[cloves, garlic],
[Italian, plum, tomatoes, coarsely],
[heavy, cream],
[salt],
[parsley]],
[[Italian, sausage],
[clove, garlic],
[broth],
[Italian, tomatoes],
[carrots],
[great, Northern, beans, undrained],
[zucchini],
[spinach, rinsed],
[black, pepper],
[salt]],
[[chicken, breast, thickness],
[salt],
[bacon],
[yellow, mustard],
[honey],
[corn, syrup],
[mayonnaise],
[onion, flakes],
[vegetable, oil],
[mushrooms],
[Colby, Monterey, Jack, cheese],
[parsley]],
[[soy, sauce],
[vegetable, oil],
[Worcestershire, sauce],
[lemon, juice],
[brown, sugar],
[ketchup],
[pork, chops]],
[[bulk, mild, Italian, sausage],
[red, pepper, flakes],
[bacon],
[onion],
[garlic],
[chicken, broth],
[potatoes, thinly],
[heavy, cream],
[bunch, spinach, tough]],
[[bacon], [little, smokie, sausages], [brown, sugar]],
[[pork, chops],
[vegetable, oil],
[brown, sugar],
[salt, pepper],
[cinnamon],
[nutmeg],
[unsalted, butter],
[tart, apples, cored],
[pecans]],
[[bacon],
[stalks, celery],
[onion],
[cloves, garlic],
[potatoes],
[chicken, stock, enough, potatoes],
[butter],
[flour],
[heavy, cream],
[tarragon],
[cilantro],
[salt, pepper]],
[[clean, new, red, potatoes],
[eggs],
[bacon],
[onion, finely],
[stalk, celery, finely],
[],
[salt, pepper]],
[[eggs, lightly],
[milk],
[Italian, bread, crumbs],
[Parmesan, cheese],
[parsley],
[olive, oil],
[cloves, garlic],
[pork, chops]],
[[pork, sausage], [pie, filling], [pie, crust], [Cheddar, cheese]],
[[shredded, brown, potatoes],
[salt],
[black, pepper],
[olive, oil],
[Cheddar, cheese],
[eggs],
[water],
[bacon],
[Cheddar, cheese]],
[[pork],
[beef],
[finely, onion],
[water],
[salt],
[pepper],
[allspice],
[cloves],
[cinnamon],
[liquid, chicken, seasoning],
[pastry, double, crust, pie]],
[[frozen, bread, dough],
[Parmesan, cheese],
[vegetable, oil],
[egg, yolks],
[parsley],
[oregano],
[garlic],
[black, pepper],
[pepperoni],
[Virginia, ham],
[provolone, cheese],
[vegetable, oil],
[green, bell, pepper],
[onion],
[mushrooms],
[egg],
[grated, Parmesan, cheese],
[Italian, seasoning]],
[[pie, crusts],
[cheese],
[eggs],
[mozzarella, cheese],
[ham],
[Genoa, salami],
[prosciutto],
[Parmesan, cheese]],
[[frozen, bread, dough],
[Parmesan, cheese],
[vegetable, oil],
[egg, yolks],
[parsley],
[oregano],
[garlic],
[black, pepper],
[pepperoni],
[Virginia, ham],
[provolone, cheese],
[vegetable, oil],
[green, bell, pepper],
[onion],
[mushrooms],
[egg],
[grated, Parmesan, cheese],
[Italian, seasoning]],
[[ham],
[minced, onion],
[poppy, seeds],
[margarine],
[biscuits, biscuits],
[Swiss, cheese],
[poppy, seeds, sprinkling]],
[[lean, pork],
[cloves],
[cinnamon],
[onion],
[salt],
[stalk, celery],
[bay],
[water],
[baking, potatoes],
[pie, crusts]],
[[flour],
[salt],
[egg],
[cold, water],
[bacon],
[potatoes],
[Cheddar, cheese],
[salt, pepper],
[bacon],
[sauerkraut, rinsed],
[sour, cream],
[salt, pepper]],
[[dish, pie, crusts],
[finely, green, bell, pepper],
[onion, finely],
[mushrooms],
[eggs],
[heavy, cream],
[Monterey, Jack, cheese],
[Swiss, cheese],
[ham],
[vinegar],
[tarragon],
[garlic],
[nutmeg],
[parsley],
[salt, pepper]],
[[flour],
[shortening],
[ice, water],
[salt],
[thinly, potatoes],
[carrots],
[onions],
[rutabaga],
[lean, beef],
[lean, pork],
[salt],
[black, pepper],
[monosodium, glutamate, MSG],
[beef, bouillon],
[hot, water]],
[[flour],
[cornmeal],
[salt],
[butter],
[eggs],
[cold, water],
[cheese],
[cheese],
[Parmesan, cheese],
[egg],
[parsley],
[basil],
[oregano],
[mozzarella, cheese],
[ham],
[spinach],
[jar, red, peppers, dry],
[egg]],
[[active, dry, yeast],
[sugar],
[warm, water],
[flour],
[milk],
[],
[shortening],
[lean, beef],
[Italian, sausage],
[onion],
[cabbage],
[mustard],
[],
[black, pepper],
[American, cheese],
[Cheddar, cheese]],
[[olive, oil],
[bulk, Italian, sausage],
[sausage, drippings],
[margarine],
[apples],
[onion],
[salt, black, pepper],
[oregano],
[flour],
[water],
[potatoes],
[margarine]],
[[vegetable, oil],
[flour],
[onion],
[bulk, pork, sausage],
[beef],
[Cajun, seasoning],
[garlic],
[store, refrigerated, pie, dough, room, temperature],
[vegetable, oil]],
[[butter], [bacon], [potatoes], [fontina, cheese], [salt, pepper]],
[[beef],
[pork],
[onion],
[green, bell, pepper],
[stalks, celery, finely],
[cloves, garlic],
[carrot, finely],
[baking, potato, finely],
[bay],
[thyme],
[parsley],
[Worcestershire, sauce],
[salt, free, seasoning],
[salt, pepper],
[beef, bouillon],
[hot, water],
[mild, Cheddar, cheese sheets, puff, pastry
egg yolk water flour shortening ice, water salt potatoes carrots onions rutabaga lean, beef lean, pork salt black, pepper monosodium, glutamate, MSG beef, bouillon water onions bacon, sour, cream, egg, flour, salt, caraway, seed]
